GET http://localhost:8080/api/init

###

GET http://localhost:8080/api/todos

###

POST http://localhost:8080/api/todos
content-type: application/json

{
    "Id": "1e4b6bc5-8eb7-46eb-a681-518c99dbcbd4",
    "Title": "a todo added from REST client",
}
